export type EasingFunction = (t: number) => number;

export type createBezier = (x1: number, y1: number, x2: number, y2: number) => EasingFunction;

export interface Config {
	default: { tension: 170; friction: 26 };
	gentle: { tension: 120; friction: 14 };
	wobbly: { tension: 180; friction: 12 };
	stiff: { tension: 210; friction: 20 };
	slow: { tension: 280; friction: 60 };
	molasses: { tension: 280; friction: 120 };
	snappy: { tension: 400; friction: 20; mass: 0.5 };
}

export interface EasingDictionary {
	easeInAcceleration: EasingFunction;
	easeInBack: EasingFunction;
	easeInBounce: EasingFunction;
	easeInCirc: EasingFunction;
	easeInCubic: EasingFunction;
	easeInDeceleration: EasingFunction;
	easeInElastic: EasingFunction;
	easeInEntranceExpressive: EasingFunction;
	easeInEntranceProductive: EasingFunction;
	easeInExitExpressive: EasingFunction;
	easeInExitProductive: EasingFunction;
	easeInExpo: EasingFunction;
	easeInFabricAccelerate: EasingFunction;
	easeInFabricDecelerate: EasingFunction;
	easeInFabricStandard: EasingFunction;
	easeInMozillaCurve: EasingFunction;
	easeInOutAcceleration: EasingFunction;
	easeInOutBack: EasingFunction;
	easeInOutBounce: EasingFunction;
	easeInOutCirc: EasingFunction;
	easeInOutCubic: EasingFunction;
	easeInOutDeceleration: EasingFunction;
	easeInOutElastic: EasingFunction;
	easeInOutEntranceExpressive: EasingFunction;
	easeInOutEntranceProductive: EasingFunction;
	easeInOutExitExpressive: EasingFunction;
	easeInOutExitProductive: EasingFunction;
	easeInOutExpo: EasingFunction;
	easeInOutFabricAccelerate: EasingFunction;
	easeInOutFabricDecelerate: EasingFunction;
	easeInOutFabricStandard: EasingFunction;
	easeInOutMozillaCurve: EasingFunction;
	easeInOutQuad: EasingFunction;
	easeInOutQuart: EasingFunction;
	easeInOutQuint: EasingFunction;
	easeInOutRevBack: EasingFunction;
	easeInOutRidiculousWiggle: EasingFunction;
	easeInOutSharp: EasingFunction;
	easeInOutSine: EasingFunction;
	easeInOutSmooth: EasingFunction;
	easeInOutSmoother: EasingFunction;
	easeInOutSoftSpring: EasingFunction;
	easeInOutSpring: EasingFunction;
	easeInOutStandard: EasingFunction;
	easeInOutStandardExpressive: EasingFunction;
	easeInOutStandardProductive: EasingFunction;
	easeInOutUWPAccelerate: EasingFunction;
	easeInQuad: EasingFunction;
	easeInQuart: EasingFunction;
	easeInQuint: EasingFunction;
	easeInRevBack: EasingFunction;
	easeInRidiculousWiggle: EasingFunction;
	easeInSharp: EasingFunction;
	easeInSine: EasingFunction;
	easeInSmooth: EasingFunction;
	easeInSmoother: EasingFunction;
	easeInSoftSpring: EasingFunction;
	easeInSpring: EasingFunction;
	easeInStandard: EasingFunction;
	easeInStandardExpressive: EasingFunction;
	easeInStandardProductive: EasingFunction;
	easeInUWPAccelerate: EasingFunction;
	easeOutAcceleration: EasingFunction;
	easeOutBack: EasingFunction;
	easeOutBounce: EasingFunction;
	easeOutCirc: EasingFunction;
	easeOutCubic: EasingFunction;
	easeOutDeceleration: EasingFunction;
	easeOutElastic: EasingFunction;
	easeOutEntranceExpressive: EasingFunction;
	easeOutEntranceProductive: EasingFunction;
	easeOutExitExpressive: EasingFunction;
	easeOutExitProductive: EasingFunction;
	easeOutExpo: EasingFunction;
	easeOutFabricAccelerate: EasingFunction;
	easeOutFabricDecelerate: EasingFunction;
	easeOutFabricStandard: EasingFunction;
	easeOutInAcceleration: EasingFunction;
	easeOutInBack: EasingFunction;
	easeOutInBounce: EasingFunction;
	easeOutInCirc: EasingFunction;
	easeOutInCubic: EasingFunction;
	easeOutInDeceleration: EasingFunction;
	easeOutInElastic: EasingFunction;
	easeOutInEntranceExpressive: EasingFunction;
	easeOutInEntranceProductive: EasingFunction;
	easeOutInExitExpressive: EasingFunction;
	easeOutInExitProductive: EasingFunction;
	easeOutInExpo: EasingFunction;
	easeOutInFabricAccelerate: EasingFunction;
	easeOutInFabricDecelerate: EasingFunction;
	easeOutInFabricStandard: EasingFunction;
	easeOutInMozillaCurve: EasingFunction;
	easeOutInQuad: EasingFunction;
	easeOutInQuart: EasingFunction;
	easeOutInQuint: EasingFunction;
	easeOutInRevBack: EasingFunction;
	easeOutInRidiculousWiggle: EasingFunction;
	easeOutInSharp: EasingFunction;
	easeOutInSine: EasingFunction;
	easeOutInSmooth: EasingFunction;
	easeOutInSmoother: EasingFunction;
	easeOutInSoftSpring: EasingFunction;
	easeOutInSpring: EasingFunction;
	easeOutInStandard: EasingFunction;
	easeOutInStandardExpressive: EasingFunction;
	easeOutInStandardProductive: EasingFunction;
	easeOutInUWPAccelerate: EasingFunction;
	easeOutMozillaCurve: EasingFunction;
	easeOutQuad: EasingFunction;
	easeOutQuart: EasingFunction;
	easeOutQuint: EasingFunction;
	easeOutRevBack: EasingFunction;
	easeOutRidiculousWiggle: EasingFunction;
	easeOutSharp: EasingFunction;
	easeOutSine: EasingFunction;
	easeOutSmooth: EasingFunction;
	easeOutSmoother: EasingFunction;
	easeOutSoftSpring: EasingFunction;
	easeOutSpring: EasingFunction;
	easeOutStandard: EasingFunction;
	easeOutStandardExpressive: EasingFunction;
	easeOutStandardProductive: EasingFunction;
	easeOutUWPAccelerate: EasingFunction;
	linear: EasingFunction;
}
